server:
  port: 8030

spring:
  application:
    name: letter-service
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB

cloud:
  aws:
    credentials:
      access-key: 
      secret-key: 
    region:
      static: ap-northeast-2
    s3:
      bucket: dear103
openai:
  api-key: 
