server:
  port: 8030

spring:
  application:
    name: letter-service
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB

cloud:
  aws:
    credentials:
      access-key: AKIAYRDREYLRMAQMXHNC
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: dear103
openai:
  api-key: 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